init_params:
  base_fun: linear
  grid: 3
  k: 3
  noise_scale: 0.1428874893358386
  noise_scale_base: 0.10755084456106999
  width:
  - 362
  - 4
  - 4
  - 1
prune_threshold: 0.011642296167148259 # since early_stopping is true, we use validation set to prune instead of this threshold
train_params:
  early_stopping: true
  lamb: 0.00918714123580676
  lamb_coef: 5
  lamb_entropy: 3
  lr: 0.014192203091072466
  steps: 300
