baseline_hazard: 0.01
log_partial_hazard: 'lambda x1, x2, x3, noise1, noise2: np.tanh(5*x1) + np.sin(2*np.pi*x2)
  + x3**2'
n_samples: 10000
ranges:
- -1
- 1
true_kan:
- - tanh
  - sin
  - x^2
  - '0'
  - '0'
