baseline_hazard: 0.01
log_partial_hazard: 'lambda x1, x2, noise1, noise2: np.tanh(5*(np.log(x1) + np.abs(x2)))'
n_samples: 10000
ranges:
- - 0.1
  - 1
- - -1
  - 1
- - -1
  - 1
- - -1
  - 1
true_kan:
- - log
  - abs
  - '0'
  - '0'
- - tanh
